apiVersion: v1
kind: Pod
metadata:
  name: yoda-service
spec:
  serviceAccountName: yoda-sa
  containers:
    - name: nginx
      image: bitnami/nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: yoda
          mountPath: /etc/yoda-service
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yoda-db-password
              key: password
  volumes:
    - name: yoda
      configMap:
        name: yoda-service-config